# service.yaml - Cloud Run configuration with secrets
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bakar
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containers:
      - image: gcr.io/YOUR-PROJECT-ID/bakar:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: GMAIL_USER
          valueFrom:
            secretKeyRef:
              name: gmail-user
              key: latest
        - name: GMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: gmail-pass
              key: latest
        - name: GMAIL_DEST_EMAIL
          valueFrom:
            secretKeyRef:
              name: gmail-dest-email
              key: latest
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"